LeastAuthority/winden

README.md
I have updated README.md to reflect current status that we are evaluating code repository and switching from vue to ReactJS
=> Update README.md to reflect current status

client/src/app/components/CodeInput.test.tsx, client/src/app/components/CodeInput.tsx, client/src/stories/CodeInput.stories.tsx
=> Allow submit on enter key

client/src/app/components/providers/WormholeProvider.tsx, client/src/app/util/actions.ts, client/src/app/util/errors.ts, client/src/app/wormhole/client_worker.ts, client/src/worker/go.d.ts, client/src/worker/index.ts
=> Add error message when wasm exits

client/src/app/components/screens/receive/ReceiveConsentScreen.tsx
=> Disable download button if already starting

client/src/public/index.html
=> Add version number to title

README.md, client/package-lock.json, client/package.json, client/src/app/components/AppTemplate.tsx, client/src/public/index.html
=> Rename to winden

client/src/app/components/screens/send/SendBeginScreen.tsx
=> Add error message on directory selection

client/src/app/components/providers/WormholeProvider.tsx, client/src/app/util/errors.ts, client/src/app/wormhole/client_worker.ts
=> Add invalid code error for sender

client-e2e/test/specs/receive.ts, client-e2e/test/specs/send.ts, client/gulpfile.js, client/src/app/components/App.tsx, client/src/app/components/CodeInput.tsx, client/src/app/components/providers/CodeInputProvider.tsx, client/src/app/components/screens/send/SendInstructionsScreen.tsx, client/src/app/hooks/useCodeUrlCheck.ts, client/src/app/index.development.tsx, client/src/app/index.production.tsx, client/src/app/wormhole/client_worker.ts
=> Reserve hash routes for codes

client/gulpfile.js
So that the .htaccess in #31 can be copied over as well
=> Allow dotfiles to be added to public folder

client/src/app/hooks/useCancelModal.ts
=> Fix cancellation workaround

client/src/app/components/screens/send/SendInstructionsScreen.tsx
=> Update code url look

client/src/app/components/providers/ErrorProvider.tsx, client/src/app/components/screens/receive/ReceiveBeginScreen.tsx, client/src/app/components/screens/send/SendBeginScreen.tsx, client/src/app/util/errors.tsx
Updated some of error messages according sheet: https://docs.google.com/spreadsheets/d/1pBWUXf7Xt8y_60JsxzdrgXmuqJuWMGXugSEG-Kjvn7o/edit#gid=0
Overall it requires separate changes and cancellation improvements in order to properly notify user what is happening.
=> Updated error messages

client/src/app/components/App.tsx, client/src/app/components/pages/Business.tsx, client/src/app/components/pages/FeedbackPage.tsx
=> Add business and feedback page

client/src/app/components/App.tsx, client/src/app/components/Dropzone.tsx, client/src/app/components/pages/TermsPage.tsx, client/src/app/components/providers/ThemeProvider.tsx, client/src/app/components/screens/receive/ReceiveConsentScreen.tsx
=> Add terms page

client/src/app/components/pages/PrivacyPage.tsx
=> Add privacy page

client/src/app/components/App.tsx, client/src/app/components/BrowserValidator.tsx, client/src/app/components/Content.tsx, client/src/app/components/Dropzone.tsx, client/src/app/components/Footer.tsx, client/src/app/components/pages/StaticPage.tsx, client/src/app/components/pages/static/about.html, client/src/app/components/pages/static/faq.html, client/src/app/components/pages/static/feedback.html, client/src/app/components/pages/static/privacy.html, client/src/app/components/providers/ThemeProvider.tsx, client/src/app/components/screens/receive/ReceiveConsentScreen.tsx, client/src/app/components/screens/send/SendBeginScreen.tsx, client/src/app/hooks/useTargetHighlights.ts
=> UI corrections

client/src/app/components/providers/ThemeProvider.tsx, client/src/app/components/providers/WormholeProvider.tsx, client/src/app/hooks/useRateLimitedState.ts, client/src/app/util/constants.ts
=> Fix transfer performance issues

.github/workflows/codeql-analysis.yml
Enabling CodeQL analysis engine for Javascript/Typescript. It is integrated in Github and recommended.
More about tool:
https://codeql.github.com/docs/codeql-overview/
Javascript/Typescript specific issues checklist:
https://github.com/github/codeql/tree/codeql-cli/latest/javascript/ql/src
Results are visible in: https://github.com/LeastAuthority/winden/security/code-scanning
=> Enable Code Scanning

.github/workflows/deploy.yml, client/gulpfile.js, client/package-lock.json, client/package.json, client/src/public/robots.prod.txt
Enabling robots.txt to allow robots to crawl over our content for production environment. 
Related with SEO optimisation task: #OP 2324
=> Enable indexing in robots.txt

.github/workflows/deploy.yml, docker-compose.yml
Fix deployment script after latest PRs.
Issue was that after mounting /usr/src/app/client there is no npm packages.
=> Fix deployment script

README.md, client/src/app/components/Footer.tsx, client/src/app/components/Navbar.tsx, client/src/app/components/screens/receive/ReceiveConsentScreen.tsx
Remove _blank for href to be ethical and compliant: https://www.w3.org/TR/WCAG20-TECHS/G200.html
Original discussion from this PR: #76
=> Remove _blank for href to be ethical and compliant

README.md, client/src/app/components/CodeInput.test.tsx, client/src/app/components/Footer.tsx, client/src/app/components/Navbar.tsx, client/src/app/components/screens/receive/ReceiveConsentScreen.tsx
Sometimes integration tests failed in Github Action, manual retry usually helped that. 
Lets try with automatic retry for jest
=> Integration tests retry

client/src/public/.htaccess
Added gzip for static resources. Helps to decrease transfer size from 10 B to 2.5 MB
=> Added gzip for static resources

README.md, client/.env.example, client/Dockerfile, client/gulpfile.js, doc/deployment-in-aws.md
Removing AWS configurations related with this task #66 
Added documentation, just to avoid digging in commits and PRs.
=> Cleanup aws deployment

.github/workflows/deploy.yml
Fix deployment to production as .env files are not set during production deployment. 
Removed wrong If statement
=> Fix deployment to prod

client/src/app/hooks/useTargetHighlights.ts, client/src/app/wormhole/client_worker.ts
A little cleanup activity, removed unnecessary console.log printing while using application.
=> Removed unnecessary console.log printing

.github/workflows/integrate.yml
Print test coverage statistics while running unit and integration tests in CI.
=> Print test coverage while running unit tests

client-e2e/package-lock.json, client-e2e/package.json, client-e2e/test/wdio.CI.conf.ts, client-e2e/test/wdio.conf.ts
lsp was reporting errors because the type package was not installed, this fixes it
=> Add @wdio/types package

client/src/app/components/pages/static/TermsPage.tsx
=> Fix typo in terms & conditions text

doc/release.md
Updated current manual release steps.
The process can be improved in future depended on needs and release frequency.
=> Add documentation about release

client/gulpfile.js, client/package-lock.json, client/package.json, client/src/app/index.tsx, client/src/app/sagas.ts, client/src/app/types/ionic.d.ts, client/tsconfig.json
Ref https://github.com/LeastAuthority/winden/issues/85
=> Remove vue dependencies

client/src/public/index.html
=> Use full URL to Twitter image (fixes #155)

client/src/app/components/pages/static/FaqPage.tsx
=> Explain the size limit in the FAQ

.github/workflows/deploy.yml, .github/workflows/integrate.yml
Closes #175
* Remove legacies and useless steps
* Consistent step and host naming
* Bump versions to avoid node-16
=> Cleanup workflows

.github/workflows/integrate.yml
=> Fix hostames

.github/workflows/deploy.yml, .github/workflows/integrate.yml, README.md, client-e2e/Dockerfile, client/Dockerfile, docker-compose.yml
=> Optimize and cache images w/o npm inside

client/Dockerfile
=> Pin rustup and wasm-pack versions

.github/workflows/deploy.yml, .github/workflows/integrate.yml, client-e2e/Dockerfile
=> Pin GitHub runner in integration workflow too
